FROM node:16.19.0-alpine3.17 as app_node

WORKDIR /srv/app

#COPY --link ../assets/ ./

#RUN npm install

EXPOSE 5173
#FROM app_node as app_node_prod

#RUN npm run build

#FROM app_node as app_node_dev

#RUN npm run dev
